services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: industrial-iot-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  postgres:
    image: postgres:17
    container_name: industrial-iot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: industrial_iot
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: industrial-iot-backend
    restart: unless-stopped
    ports:
      - "8000:8000"

    environment:
      MQTT_BROKER: mqtt
      MQTT_PORT: 1883
      MQTT_TOPIC: industrial/equipment/telemetry

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: industrial_iot
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password

    depends_on:
      - mqtt
      - postgres

volumes:
  postgres_data: